services:
  - type: web
    name: fastapi-randomizer
    env: python
    pythonVersion: 3.13
    plan: free
    buildCommand: pip install uv && uv sync
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
