services:
  - type: web
    name: fastapi-randomizer
    env: python
    pythonVersion: 3.13
    plan: free
    buildCommand: uv sync --frozen && uv cache prune --ci
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
